import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BarChart3, BookOpen, ChevronRight, FolderOpen, GraduationCap, Medal, Plus, RotateCcw, Search, ShieldCheck, SlidersHorizontal, Sparkles, Star, UsersRound } from "lucide-react";

import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { KpiCard } from "@/components/ui/kpi-card";
import { Select } from "@/components/ui/select";
import { StatusBadge } from "@/components/ui/status-badge";
import type { CourseStatus } from "@/generated/prisma/enums";
import { computeQualityScore, qualityTierColor } from "@/lib/courses/quality-score";
import { getAdminCoursesDashboardData, listAdminCourses, type AdminCourseRow } from "@/server/queries/admin-courses";
import { listFeaturedCategories } from "@/server/queries/categories";

export const metadata: Metadata = { title: "Cours — CRM admin" };
export const dynamic = "force-dynamic";

interface Params { q?: string; status?: CourseStatus; categoryId?: string; instructorId?: string; featured?: string; page?: string }

export default async function AdminCoursesPage({ searchParams }: { searchParams: Promise<Params> }) {
  const params = await searchParams;
  const filters = { q: params.q, status: params.status, categoryId: params.categoryId, instructorId: params.instructorId, featured: params.featured === "1" ? true : params.featured === "0" ? false : undefined, page: Number(params.page) || 1, pageSize: 25 };
  const [{ rows, total, page, pageSize }, categories, dashboard] = await Promise.all([listAdminCourses(filters), listFeaturedCategories(100), getAdminCoursesDashboardData()]);
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const hasFilters = Boolean(params.q || params.status || params.categoryId || params.instructorId || params.featured);

  return <div className="space-y-5" data-testid="courses-workspace">
    <header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700 ring-1 ring-inset ring-emerald-200 dark:bg-emerald-500/10 dark:text-emerald-300"><BookOpen className="h-6 w-6" /></span><div><h1 className="text-2xl font-semibold tracking-tight">Cours</h1><p className="mt-0.5 text-sm text-muted-foreground">{dashboard.stats.total} cours · catalogue, qualité et diffusion.</p></div></div><div className="grid w-full gap-2 sm:flex sm:w-auto"><Button asChild variant="outline"><Link href="/admin/cours/moderation"><ShieldCheck className="h-4 w-4" />File de modération{dashboard.stats.pending ? ` (${dashboard.stats.pending})` : ""}</Link></Button><Button asChild variant="outline"><Link href="/admin/cours/featured"><Star className="h-4 w-4" />Cours en vedette</Link></Button></div></header>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-5" aria-label="Statistiques des cours"><KpiCard label="Total des cours" value={dashboard.stats.total} icon={<BookOpen className="h-5 w-5" />} tone="blue" hint={`${dashboard.stats.draft} brouillon${dashboard.stats.draft > 1 ? "s" : ""}`} appearance="crm" /><KpiCard label="Cours publiés" value={dashboard.stats.published} icon={<Medal className="h-5 w-5" />} tone="emerald" hint={percentage(dashboard.stats.published, dashboard.stats.total)} href="/admin/cours?status=PUBLISHED" appearance="crm" /><KpiCard label="Élèves inscrits" value={dashboard.stats.enrollments} icon={<UsersRound className="h-5 w-5" />} tone="sky" hint="Inscriptions cumulées" appearance="crm" /><KpiCard label="Note moyenne" value={dashboard.stats.averageRating ? `${dashboard.stats.averageRating.toFixed(1)}/5` : "—"} icon={<Star className="h-5 w-5" />} tone="amber" hint="Cours ayant reçu des avis" appearance="crm" /><KpiCard label="Score qualité moyen" value={dashboard.stats.averageQuality === null ? "—" : `${dashboard.stats.averageQuality}/100`} icon={<Sparkles className="h-5 w-5" />} tone="sky" hint={dashboard.stats.scoredCount ? `${dashboard.stats.scoredCount} cours évaluables` : "Signal encore insuffisant"} appearance="crm" /></section>

    <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_19rem]"><section className="min-w-0 overflow-hidden rounded-2xl border border-border/75 bg-card shadow-[0_10px_35px_rgba(15,23,42,0.05)]"><CourseFilters params={params} categories={categories} instructors={dashboard.instructors} hasFilters={hasFilters} />
      {rows.length ? <><div className="hidden overflow-x-auto md:block"><CoursesTable rows={rows} /></div><div className="divide-y divide-border/60 md:hidden">{rows.map((course) => <CourseMobileCard key={course.id} course={course} />)}</div></> : <div className="p-5"><EmptyState icon={<BookOpen className="h-6 w-6" />} title="Aucun cours trouvé" description={hasFilters ? "Modifiez ou réinitialisez les filtres pour élargir la recherche." : "Aucun cours n’est encore disponible dans le catalogue."} action={<Button asChild><Link href="/formateur/cours/nouveau">Créer un cours</Link></Button>} /></div>}
      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-border/70 px-4 py-3 text-xs text-muted-foreground"><span>{total ? `Affichage de ${(page - 1) * pageSize + 1} à ${Math.min(page * pageSize, total)} sur ${total} cours` : "Aucun résultat"}</span>{totalPages > 1 ? <Pagination params={params} page={page} totalPages={totalPages} /> : null}</footer></section>
      <CoursesSidebar dashboard={dashboard} />
    </div>
  </div>;
}

function CourseFilters({ params, categories, instructors, hasFilters }: { params: Params; categories: Array<{ id: string; name: string }>; instructors: Array<{ id: string; name: string | null; email: string }>; hasFilters: boolean }) { return <form className="grid gap-3 border-b border-border/70 p-4 sm:grid-cols-2 xl:grid-cols-4" role="search"><div className="relative sm:col-span-2"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input name="q" aria-label="Rechercher un cours" defaultValue={params.q ?? ""} placeholder="Titre ou slug du cours…" className="pl-9" /></div><Select name="status" defaultValue={params.status ?? ""} aria-label="Statut"><option value="">Tous les statuts</option><option value="DRAFT">Brouillons</option><option value="PENDING_REVIEW">En modération</option><option value="PUBLISHED">Publiés</option><option value="REJECTED">Rejetés</option><option value="ARCHIVED">Archivés</option></Select><Select name="categoryId" defaultValue={params.categoryId ?? ""} aria-label="Catégorie"><option value="">Toutes les catégories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select><Select name="instructorId" defaultValue={params.instructorId ?? ""} aria-label="Formateur"><option value="">Tous les formateurs</option>{instructors.map((instructor) => <option key={instructor.id} value={instructor.id}>{instructor.name ?? instructor.email}</option>)}</Select><Select name="featured" defaultValue={params.featured ?? ""} aria-label="Mise en avant"><option value="">Vitrine : tous</option><option value="1">En vedette</option><option value="0">Hors vedette</option></Select><div className="flex gap-2 sm:col-span-2 xl:col-span-4"><Button type="submit"><SlidersHorizontal className="h-4 w-4" />Filtrer</Button>{hasFilters ? <Button variant="outline" size="icon" asChild><Link href="/admin/cours" aria-label="Réinitialiser"><RotateCcw className="h-4 w-4" /></Link></Button> : null}</div></form>; }
function CoursesTable({ rows }: { rows: AdminCourseRow[] }) { return <table className="w-full min-w-[68rem] text-sm"><thead className="border-b border-border bg-muted/35 text-left text-[10px] uppercase tracking-[.08em] text-muted-foreground"><tr><th className="px-4 py-3">Cours</th><th className="px-4 py-3">Statut</th><th className="px-4 py-3">Formateur</th><th className="px-4 py-3">Catégorie</th><th className="px-4 py-3 text-right">Élèves</th><th className="px-4 py-3 text-right">Note</th><th className="px-4 py-3">Score qualité</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-border/60">{rows.map((course) => <tr key={course.id} className="hover:bg-muted/35"><td className="px-4 py-3"><div className="flex items-center gap-3"><CourseIcon course={course} /><div className="min-w-0"><Link href={`/admin/cours/${course.id}`} className="block max-w-64 truncate font-semibold hover:underline">{course.title}</Link><p className="max-w-64 truncate text-[10px] text-muted-foreground">{course.slug}{course.isFeatured ? " · En vedette" : ""}</p></div></div></td><td className="px-4 py-3"><CourseStatusBadge status={course.status} /></td><td className="px-4 py-3 text-muted-foreground">{course.instructor.name ?? course.instructor.email}</td><td className="px-4 py-3 text-muted-foreground">{course.category.name}</td><td className="px-4 py-3 text-right font-semibold tabular-nums">{course.totalEnrollments.toLocaleString("fr-FR")}</td><td className="px-4 py-3 text-right tabular-nums">{course.totalRatings ? `${course.averageRating.toFixed(1)} ★` : "—"}</td><td className="px-4 py-3"><QualityScoreBadge course={course} /></td><td className="px-4 py-3 text-right"><Button variant="ghost" size="sm" asChild><Link href={`/admin/cours/${course.id}`}>Détail</Link></Button></td></tr>)}</tbody></table>; }
function CourseMobileCard({ course }: { course: AdminCourseRow }) { return <Link href={`/admin/cours/${course.id}`} className="block p-4 hover:bg-muted/35"><div className="flex gap-3"><CourseIcon course={course} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h2 className="truncate font-semibold">{course.title}</h2><CourseStatusBadge status={course.status} /></div><p className="truncate text-xs text-muted-foreground">{course.instructor.name ?? course.instructor.email} · {course.category.name}</p><div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><span>{course.totalEnrollments} élèves</span><span>{course.totalRatings ? `${course.averageRating.toFixed(1)} ★` : "Sans avis"}</span><QualityScoreBadge course={course} /></div></div></div></Link>; }
function CoursesSidebar({ dashboard }: { dashboard: Awaited<ReturnType<typeof getAdminCoursesDashboardData>> }) { const actions = [{ href: "/formateur/cours/nouveau", icon: Plus, title: "Créer un cours", text: "Ajouter un nouveau cours" }, { href: "/admin/cours/moderation", icon: ShieldCheck, title: "Modération", text: `${dashboard.stats.pending} cours à examiner` }, { href: "/admin/cours/featured", icon: Star, title: "Cours en vedette", text: `${dashboard.stats.featured} cours dans la vitrine` }, { href: "/admin/categories", icon: FolderOpen, title: "Catégories", text: "Organiser le catalogue" }, { href: "/admin/analytics/apprentissage", icon: BarChart3, title: "Statistiques", text: "Analyser les performances" }]; return <aside className="space-y-4 xl:sticky xl:top-4"><div className="rounded-2xl border border-border/75 bg-card p-5 shadow-[0_10px_35px_rgba(15,23,42,0.05)]"><h2 className="font-semibold">Actions rapides</h2><div className="mt-3 divide-y divide-border/60">{actions.map(({ href, icon: Icon, title, text }) => <Link key={title} href={href} className="group flex items-center gap-3 py-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300"><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold group-hover:underline">{title}</span><span className="block truncate text-xs text-muted-foreground">{text}</span></span><ChevronRight className="h-4 w-4 text-muted-foreground" /></Link>)}</div></div><div className="rounded-2xl border border-border/75 bg-card p-5 shadow-[0_10px_35px_rgba(15,23,42,0.05)]"><h2 className="font-semibold">Répartition des statuts</h2><div className="mt-4 flex items-center gap-5"><StatusDonut stats={dashboard.stats} /><ul className="flex-1 space-y-2 text-xs"><Legend color="bg-emerald-500" label="Publiés" value={dashboard.stats.published} /><Legend color="bg-amber-500" label="Brouillons" value={dashboard.stats.draft} /><Legend color="bg-violet-500" label="À modérer" value={dashboard.stats.pending} /><Legend color="bg-slate-400" label="Autres" value={dashboard.stats.archived + dashboard.stats.rejected} /></ul></div></div><div className="rounded-2xl border border-border/75 bg-card p-5 shadow-[0_10px_35px_rgba(15,23,42,0.05)]"><h2 className="font-semibold">Top catégories</h2><ul className="mt-4 space-y-3">{dashboard.topCategories.map((category) => <li key={category.id}><div className="mb-1 flex justify-between gap-2 text-xs"><Link href={`/admin/cours?categoryId=${category.id}`} className="truncate font-medium hover:underline">{category.name}</Link><span className="tabular-nums text-muted-foreground">{category.count}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.max(5, category.count / Math.max(dashboard.stats.total, 1) * 100)}%` }} /></div></li>)}</ul></div></aside>; }
function StatusDonut({ stats }: { stats: Awaited<ReturnType<typeof getAdminCoursesDashboardData>>["stats"] }) { const total = Math.max(stats.total, 1); const published = stats.published / total * 100; const draft = stats.draft / total * 100; const pending = stats.pending / total * 100; return <div className="relative h-24 w-24 shrink-0 rounded-full" style={{ background: `conic-gradient(#10b981 0 ${published}%, #f59e0b ${published}% ${published + draft}%, #8b5cf6 ${published + draft}% ${published + draft + pending}%, #94a3b8 ${published + draft + pending}% 100%)` }} role="img" aria-label={`${stats.published} cours publiés sur ${stats.total}`}><span className="absolute inset-[14px] flex items-center justify-center rounded-full bg-card text-xs font-bold">{Math.round(published)}%</span></div>; }
function Legend({ color, label, value }: { color: string; label: string; value: number }) { return <li className="flex items-center justify-between"><span className="flex items-center gap-2 text-muted-foreground"><span className={`h-2.5 w-2.5 rounded-full ${color}`} />{label}</span><strong>{value}</strong></li>; }
function CourseIcon({ course }: { course: AdminCourseRow }) { const Icon = course.isFeatured ? Star : course.status === "PUBLISHED" ? BookOpen : GraduationCap; return <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-blue-100 to-emerald-100 text-blue-700 dark:from-blue-500/20 dark:to-emerald-500/20 dark:text-blue-300"><Icon className="h-4 w-4" /></span>; }
function CourseStatusBadge({ status }: { status: CourseStatus }) { if (status === "PUBLISHED") return <StatusBadge tone="success">Publié</StatusBadge>; if (status === "PENDING_REVIEW") return <StatusBadge tone="warning">À valider</StatusBadge>; if (status === "REJECTED") return <StatusBadge tone="danger">Rejeté</StatusBadge>; if (status === "ARCHIVED") return <StatusBadge tone="neutral">Archivé</StatusBadge>; return <StatusBadge tone="neutral">Brouillon</StatusBadge>; }
function QualityScoreBadge({ course }: { course: Pick<AdminCourseRow, "averageRating" | "totalEnrollments" | "totalRatings"> }) { const result = computeQualityScore(course); return <span className={`inline-flex items-center gap-1 rounded-md px-2 py-1 text-[10px] font-semibold tabular-nums ${qualityTierColor(result.tier)}`} title={result.reason}>{result.tier === "indéfini" ? "—" : <><span>{result.score}</span><span className="uppercase opacity-75">{result.tier}</span></>}</span>; }
function Pagination({ params, page, totalPages }: { params: Params; page: number; totalPages: number }) { const href = (next: number) => { const search = new URLSearchParams(); for (const [key, value] of Object.entries(params)) if (value && key !== "page") search.set(key, value); search.set("page", String(next)); return `/admin/cours?${search}`; }; return <nav className="flex items-center gap-1" aria-label="Pagination des cours"><Button size="icon" variant="outline" className="h-8 w-8" asChild={page > 1} disabled={page <= 1}>{page > 1 ? <Link href={href(page - 1)}><ArrowLeft className="h-4 w-4" /></Link> : <ArrowLeft className="h-4 w-4" />}</Button><strong className="px-2 text-foreground">{page} / {totalPages}</strong><Button size="icon" variant="outline" className="h-8 w-8" asChild={page < totalPages} disabled={page >= totalPages}>{page < totalPages ? <Link href={href(page + 1)}><ArrowRight className="h-4 w-4" /></Link> : <ArrowRight className="h-4 w-4" />}</Button></nav>; }
function percentage(value: number, total: number) { return total ? `${Math.round(value / total * 100)} % du catalogue` : "Catalogue vide"; }
